### ISSUE TITLE
Stretch: Tracking Fishing

### ISSUE THREAD

**Issue by BenJarrett** [BenJarrett/ASSIGNMENT-Bear-Watcher#11]
- [ ] As a user, I should be able to click something on each bear to indicate it has just tried to catch a fish.
- [ ] As a user, I should be able to click something on each bear to indicate it has just successfully caught a fish.
- [ ] As a user, looking at a bear card I should see time stamps and statuses for each time a bear caught a fish or attempted to catch a fish
- [ ] As a user, looking at a bear card, I should see a total number of fish caught tally.
